# pubspec.yaml の内容を以下に更新します
name: sukekenn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase 関連 (バージョンは既存のものに合わせています)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.1.0 # 新規追加: 画像アップロード用
  firebase_messaging: ^15.0.0 # 新規追加: 通知機能用
  firebase_crashlytics: ^4.0.0 # 新規追加: クラッシュレポート用
  firebase_performance: ^0.10.0 # 新規追加: パフォーマンスモニタリング用
  firebase_analytics: ^11.0.0 # 新規追加: アナリティクス用

  # 状態管理 (Riverpod)
  flutter_riverpod: ^2.5.1 # 新規追加
  riverpod_annotation: ^2.3.5 # 新規追加
  freezed_annotation: ^2.4.1 # 新規追加: データクラス生成用
  json_annotation: ^4.9.0 # 新規追加: JSONシリアライズ/デシリアライズ用

  # カレンダーUI
  table_calendar: ^3.1.1 # 新規追加
  intl: ^0.19.0 # バージョンを更新 (0.18.1 -> 0.19.0)

  # UI/UX & その他ユーティリティ
  flutter_slidable: ^3.0.1 # 新規追加: スワイプアクション用
  image_picker: ^1.1.2 # 新規追加: 画像選択用
  # image_cropper: ^5.0.0 # 必要なら追加 (今回は含まず)
  # cached_network_image: ^3.3.1 # 必要なら追加 (今回は含まず)
  url_launcher: ^6.3.0 # 新規追加: 外部URLを開く
  share_plus: ^7.2.2 # 新規追加: 共有機能
  # qr_code_scanner: ^1.0.0 # QRコード読み取り (必要なら追加)
  # qr_flutter: ^4.1.0 # QRコード生成 (必要なら追加)
  uuid: ^4.4.0 # 新規追加: ユニークID生成
  equatable: ^2.0.5 # 新規追加: オブジェクト比較
  logger: ^2.3.0 # 新規追加: ログ出力
  permission_handler: ^11.3.1 # 新規追加: パーミッション管理

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # コード生成ツール
  build_runner: ^2.4.9 # 新規追加
  freezed: ^2.5.2 # 新規追加
  json_serializable: ^6.8.0 # 新規追加
  riverpod_generator: ^2.4.5 # 新規追加

flutter:
  uses-material-design: true