// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGX2RbbV79Z1L8luRB_S4n6lmbBSXVG8',
    appId: '1:721151707463:web:14ac9febde17cb52b8e462',
    messagingSenderId: '721151707463',
    projectId: 'calendar-match-app',
    authDomain: 'calendar-match-app.firebaseapp.com',
    storageBucket: 'calendar-match-app.firebasestorage.app',
    measurementId: 'G-8EYCZSEDK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4iG11U0ZFNeUzTCLDxvvV8eTu4Hn4HPg',
    appId: '1:721151707463:android:e3ededee6335210cb8e462',
    messagingSenderId: '721151707463',
    projectId: 'calendar-match-app',
    storageBucket: 'calendar-match-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Xp1pulGlj3-wd78F2KkbGwY8kIhseT8',
    appId: '1:721151707463:ios:d6ae527071b0662cb8e462',
    messagingSenderId: '721151707463',
    projectId: 'calendar-match-app',
    storageBucket: 'calendar-match-app.firebasestorage.app',
    iosBundleId: 'com.hiroshi.sukekenn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Xp1pulGlj3-wd78F2KkbGwY8kIhseT8',
    appId: '1:721151707463:ios:d6ae527071b0662cb8e462',
    messagingSenderId: '721151707463',
    projectId: 'calendar-match-app',
    storageBucket: 'calendar-match-app.firebasestorage.app',
    iosBundleId: 'com.hiroshi.sukekenn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYGX2RbbV79Z1L8luRB_S4n6lmbBSXVG8',
    appId: '1:721151707463:web:9cbf0fbee9afe269b8e462',
    messagingSenderId: '721151707463',
    projectId: 'calendar-match-app',
    authDomain: 'calendar-match-app.firebaseapp.com',
    storageBucket: 'calendar-match-app.firebasestorage.app',
    measurementId: 'G-LDZDDRB2X6',
  );

}